export const GOOGLE_SIGN_START = 'GOOGLE_SIGN_START';
export const EMAIL_SIGN_START = 'EMAIL_SIGN_START';

export const SIGN_SUCCESS = 'SIGN_SUCCESS';
export const SIGN_FAILURE = 'SIGN_FAILURE';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
